### ISSUE TITLE
Implement "update"-feature

### ISSUE THREAD

**Issue by wneessen** [wneessen/IperBackup#3]
If you fetched your docs and would like to resume the run, currently the script fetches the same files again. This causes double traffic.

**Comment by maxheadroom** [comment]
I guess it not only causes double traffic but will also duplicate the files on your local disk as it just adds a timestamp to the filename if that name exists

**Comment by wneessen** [comment]
This has been implemented. The "update" feature is enabled by default and will skip files, that have been downloaded already. If the -ts/--timestamp switch is provided, the old behavior will be activated.

https://github.com/wneessen/IperBackup/commit/ded5ba9832290eb0c3c5d667845be4186463a53c
