### ISSUE TITLE
make saving permission the default behaviour

### ISSUE THREAD

**Issue by maxheadroom** [wneessen/IperBackup#4]
as the "-p" switch will result in a different naming scheme for the local files I propose to make this the default behavior. IperBackup should save the permissions by default on download. From my POV this doesn't have a negative effect (although it might be an additional API call by default then).

**Comment by wneessen** [comment]
Yeah, works for me. Will be implemented

**Comment by wneessen** [comment]
Permission fetching is enabled by default now. The -p or --nopermission switch will disable this behavior no.

https://github.com/wneessen/IperBackup/commit/771216054367f2a4a9f3bfdb2879458bfda8d3d3
